### ISSUE TITLE
Could you please share the code on how to get semantic and spatial information in the .hdf5 files?

### ISSUE THREAD

**Issue by haoopan** [linjieli222/VQA_ReGAT#10]
Hi, this is a great job. I' very interested in the 'image_adj_matrix' and 'semantic_adj_matrix' which represent the spatial and semantic information,respectively. But in your project, this two important information had write in the .hdf5 files, so could you please share the code or pretrained models on how to get this two information. I'm looking forward for your reply, thanks!
Best wishes for you!

**Comment by LinkToPast1990** [comment]
Same question here...

**Comment by linjieli222** [comment]
Hi, 

Thank you for your interests in this project and sorry about the slow response.

For spatial adj matrix, please refer to #9 
For semantic adj matrix, we are not releasing the model at the moment. But it is a very small and simple classification model trained on Visual Genome, you can refer to this paper:
http://openaccess.thecvf.com/content_ECCV_2018/papers/Ting_Yao_Exploring_Visual_Relationship_ECCV_2018_paper.pdf
