### ISSUE TITLE
Where do you add b_{lab(i,j)} to your value term (see eq{2} in the paper)

### ISSUE THREAD

**Issue by dexter1691** [linjieli222/VQA_ReGAT#11]
Hi Authors, 

Thanks for releasing the code! This is very helpful. 

I was wondering where do you add the bias term $b_{lab(i,j)}$ as mentioned in equation 2 of your paper in this code. 

I was looking at Line 155 here:
https://github.com/linjieli222/VQA_ReGAT/blob/master/model/graph_att_layer.py#L155

It seems like the attention weights are directly multiplied to Value vector. If you can point us to where in the code are you adding the bias term $b_{lab}$, that will be great. 

Thanks!

**Comment by linjieli222** [comment]
Hi,

Thanks for your interests in this project. Sorry about the confusion, our implementation is slightly different from the equation in our paper

Please take at look at this line:
https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/graph_att_layer.py#L144
