### ISSUE TITLE
about spa_adj_matrix & sem_adj_matrix

### ISSUE THREAD

**Issue by fi94** [linjieli222/VQA_ReGAT#13]
Sincerely thank for your sharing codes.

I have some questions about adjacency matrix generation. Generally, semantic graph is directed, and spatial one is undirected graph. So I want to know how to generate both adjacency matrix. Could you share the codes of them?

**Comment by linjieli222** [comment]
Hi,

Thank you for your interests in this project and sorry about the slow response.

For spatial adj matrix, please refer to #9
For semantic adj matrix, we are not releasing the model at the moment. But it is a very small and simple classification model trained on Visual Genome, you can refer to this paper:
http://openaccess.thecvf.com/content_ECCV_2018/papers/Ting_Yao_Exploring_Visual_Relationship_ECCV_2018_paper.pdf
