### ISSUE TITLE
The difference between implicit relation and spatial relation.

### ISSUE THREAD

**Issue by yinyueqin** [linjieli222/VQA_ReGAT#15]
Sincerely thank for your sharing codes.

Also I am not clear about the difference between implicit relation and spatial relation. As implicit relation uses bbox coordinate to calculate bbox weight in order to calculate relative geometric position, at the same time, the spatial relation uses bbox coordinate to build spatial graph in order to calculate attention, so is there a fundamental difference between these two?

**Comment by linjieli222** [comment]
Thank you for your question and sorry for the late reply.

Implicit relation not only takes in bbox features but also considers region features, while spatial graph was built only based on relative positions between bboxes.
