### ISSUE TITLE
Code for learned image and question attentions

### ISSUE THREAD

**Issue by yinyueqin** [linjieli222/VQA_ReGAT#17]
Dear author, you showed some examples of learned image attentions (Figure 4).
Can you post the code you used to extract and create the learned image  attentions? Thank you!

**Comment by linjieli222** [comment]
Thanks for your interests in this project and sorry for the late reply. We don't have the script ready for release. But I have compiled some pointers below, hope they can help.

You can follow these code examples for drawing [bounding boxes](https://stackoverflow.com/questions/37435369/matplotlib-how-to-draw-a-rectangle-on-image), [text boxes](https://matplotlib.org/3.1.1/gallery/recipes/placing_text_boxes.html) and [attention map](https://github.com/facebookresearch/mmf/issues/145#issuecomment-518904911).
