### ISSUE TITLE
download.sh

### ISSUE THREAD

**Issue by Zou-123** [linjieli222/VQA_ReGAT#19]
Hi, I don't understand the two identical download codes......

# VQA cp-v2 Annotations
mkdir data/cp_v2_annotations
wget -P data/cp_v2_annotations https://computing.ece.vt.edu/~aish/vqacp/vqacp_v2_train_annotations.json 
wget -P data/cp_v2_annotations https://computing.ece.vt.edu/~aish/vqacp/vqacp_v2_train_annotations.json

**Comment by linjieli222** [comment]
Sorry about that. The second one should be https://computing.ece.vt.edu/~aish/vqacp/vqacp_v2_test_annotations.json.

Thanks for pointing out.

**Comment by ichigo2077** [comment]
您好啊，我想下载cp_v2_annotations 和cp_v2_questions这两个数据集，原始的链接好像很慢，您这里有其他下载的方式吗
Hello, I want to download cp_v2_annotations and cp_v2_questions these two datasets, the original link seems to be very slow, do you have other ways to download here? Thank you
谢谢您了哈。

**Comment by linjieli222** [comment]
Thanks for your interests in our work. 

Sorry to hear about the trouble in downloading cpv2 annotations/questions. We directly download them from the original server, which is pretty fast on our end. We are not aware of other ways of downloading.
