### ISSUE TITLE
Code for extracting image features

### ISSUE THREAD

**Issue by paper-coder** [linjieli222/VQA_ReGAT#20]
Could you provide the Code for extracting image features for this paper ?

**Comment by linjieli222** [comment]
Thanks for your interests in this project. As mentioned in README, our implementation uses the pretrained features from [bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention), the adaptive 10-100 features per image. Please refer to the original repo of bottom-up-attention for feature extraction code.

Thanks,
Linjie
