### ISSUE TITLE
How can I compute sem_adj_matrix, spa_adj_matrix ？

### ISSUE THREAD

**Issue by phellonchen** [linjieli222/VQA_ReGAT#21]
How can I compute sem_adj_matrix, spa_adj_matrix ？Where is the related code ？

**Comment by linjieli222** [comment]
Thanks for your interests in this project.


For spatial adj matrix, please refer to #9 
For semantic adj matrix, we are not releasing the model at the moment. But it is a very small and simple classification model trained on Visual Genome, you can refer to this paper:
[Ting_Yao_Exploring_Visual_Relationship_ECCV_2018](http://openaccess.thecvf.com/content_ECCV_2018/papers/Ting_Yao_Exploring_Visual_Relationship_ECCV_2018_paper.pdf)
