### ISSUE TITLE
loading features from the fixed h5 file

### ISSUE THREAD

**Issue by Zou-123** [linjieli222/VQA_ReGAT#22]
Hi lin! thanks your code
when I used the fixed image features from the h5 file , I got the error as follow:
loading dictionary from data/glove/dictionary.pkl
loading features from h5 file
Traceback (most recent call last):
  File "/home/xatu/anaconda2/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/xatu/anaconda2/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'data/Bottom-up-features-adaptive/train36.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

but the adaptive image features is good, can you give me some resolution? thank you very much!

**Comment by linjieli222** [comment]
Thanks for your interests in this project.

When downloading fixed image features, it is saved into ``data/Bottom-up-features-fixed``.
https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/tools/download.sh#L59-L64

And if you set adaptive to False, dataset.py would directly load from ``data/Bottom-up-features-fixed``
https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/dataset.py#L255-L256

I suspect that you have not properly set adaptive to False, therefore it is loading from the wrong directory.
