### ISSUE TITLE
Training confusion

### ISSUE THREAD

**Issue by bobo123yhb** [linjieli222/VQA_ReGAT#23]
During training, when constructing the model, do you decide to use val_dset?
model = build_regat(val_dset, args).to(device)

**Comment by linjieli222** [comment]
Thanks for your interests in this project. 

I am not sure I understand your question.  We pass val_dset into build_regat as there are some dataset related arguments that need to be loaded from dataset. e.g.: [num_tokens](https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/regat.py#L79), [visual_feature_dimension](https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/regat.py#L86), [num_ans_candidates](https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/regat.py#L118) and etc.

You can certainly use train_dset to build_regat or simply use the actual value to set the corresponding arguments. Feel free to change this part of the code into the way you would prefer.

Thanks
