### ISSUE TITLE
Some questions about the union bounding box feature vector for classifer mode 

### ISSUE THREAD

**Issue by HeartFu** [linjieli222/VQA_ReGAT#24]
Hi author,

I'm very interested in your paper and I want to use it for another model. 

But I'm a little confused about union bounding box feature vector. How to get the union bounding box features from two regions feature maps? Because the bottom-up attention just provided the regions feature maps and didn't provide the union bounding boxes features.

Does it mean we should use the pre-trained Faster-RCNN model to extract the features then mapping the union bounding boxes to the feature maps?

Thanks.

**Comment by linjieli222** [comment]
Thanks for your interests in this project and sorry for the late reply.

Yes, you will need to re-extract the union bb features from the Faster RCNN model.

Linjie
