### ISSUE TITLE
Load the cake/val_target. pkl

### ISSUE THREAD

**Issue by bobo123yhb** [linjieli222/VQA_ReGAT#25]
When the cake/val_target.pkl file is loaded, some labels appear with no content.But I looked at the Annotations in the official website, and saw that your answer differs from it.For example, question_id=393225000,answer=foodiebakercom.But your labels:[].There are also certain labels that appear differently than you gave them. For example, question_id:393225001,label=4 should correspond to 55.

**Comment by linjieli222** [comment]
We follow [ban-vqa](https://github.com/jnhwkim/ban-vqa) to process the label2ans. To elaborate, those answers that appears < 9 times in the training set are discarded, which results in about ~3000 answers. Also, the answers are normalized as shown in tools/compute_softscore.py.

For more information, you can either directly visit the official repo of ban-vqa or read carefully about answer/label processing in Section 4.1 of our paper. 

Thanks!
