### ISSUE TITLE
Does the setting of num_workers in DataLoder affect the final result？

### ISSUE THREAD

**Issue by bobo123yhb** [linjieli222/VQA_ReGAT#27]
Hello, I am very interested in your work, I have a question about does the setting of num_workers in DataLoder affect the final result？Due to my own workstation problem, I had to set num_workers=0 in Dataloder, otherwise I would report an error.

**Comment by linjieli222** [comment]
Num_workers should not affect the final results. However, it may affect the training speed. Intuitively, the number of workers is the number of parallel processes to load the data.
