### ISSUE TITLE
Test with new images

### ISSUE THREAD

**Issue by pqviet** [linjieli222/VQA_ReGAT#3]
Can you provide the pretrained model for generating visual features, so that I can test with new images?

**Comment by linjieli222** [comment]
The visual features are extracted using [bottom-up-attention model ](https://github.com/peteanderson80/bottom-up-attention).  

You should be able to directly test with implicit relation. 

For spatial relation, look into [build_graph function](https://github.com/linjieli222/VQA_ReGAT/blob/master/model/position_emb.py#L41) to extract spatial relations. 

For semantic relation, we are not releasing the semantic relation classifier at this moment. 

Thanks!
