### ISSUE TITLE
Questions for categories

### ISSUE THREAD

**Issue by zyxyling** [linjieli222/VQA_ReGAT#31]
Dear scholar, I want to ask you where can i find the 11 different categories for Spatial Graph and 14 different categories for semantic Graph ? Thanks.

**Comment by linjieli222** [comment]
Thanks for your interests in this project.

For spatial graph, please refer to #9
For semantic graph, we took the top 14 relations in Visual Genome Dataset.

**Comment by zyxyling** [comment]
Thank you very much !
