### ISSUE TITLE
pos_box/bb

### ISSUE THREAD

**Issue by bobo123yhb** [linjieli222/VQA_ReGAT#32]
I want to know the meaning of pos_boxes?
When it is adaptive, that the number of bounding boxes is free, how can the final bounding boxes be obtained from pos_boxes?

**Comment by linjieli222** [comment]
Hi,

Thanks for your interests in this project. Our adaptive feature files are constructed following BAN-VQA. For more information, please refer to the original pre-processing script in their released code: https://github.com/jnhwkim/ban-vqa/blob/master/tools/adaptive_detection_features_converter.py

**Comment by linjieli222** [comment]
Closed due to inactivity...
