### ISSUE TITLE
NOthing

### ISSUE THREAD

**Issue by alice-cool** [linjieli222/VQA_ReGAT#34]
Thanks for your perfect work！
![image](https://user-images.githubusercontent.com/16870890/114487294-ef81ca80-9c41-11eb-9da7-5067aaca3d40.png)

**Comment by linjieli222** [comment]
Thank you for pointing it out. You are definitely right. 

However, I don't think the current version would cause any error as we initialize q_dim to be the same as num_hid 
https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/regat.py#L115

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/116780135-1f87f500-aaad-11eb-8142-f4725565129e.png)
![image](https://user-images.githubusercontent.com/16870890/116780151-43e3d180-aaad-11eb-9017-65ca2f576c75.png)
![image](https://user-images.githubusercontent.com/16870890/116780160-565e0b00-aaad-11eb-9221-b07ef5e7566d.png)
Dear  scholar,
I feel the third picture could not corespond with the first formation.
![image](https://user-images.githubusercontent.com/16870890/116780188-97561f80-aaad-11eb-9cc5-c74a29234485.png)
I think the sum signal is some confused. Because in this code the visual data wasn't injected. I think maybe when injecting the visual data , the label_biases_att could be introduced( the label num is converted to the bias term)
The below picture is from https://github.com/linjieli222/VQA_ReGAT/blob/master/model/graph_att_layer.py

**Comment by alice-cool** [comment]
I found the word westerhof has error
So could I simply erase the /x185
![image](https://user-images.githubusercontent.com/16870890/121982460-1b483a80-cdc2-11eb-9a3e-142fafb3bdf3.png)
