### ISSUE TITLE
How to test your model with image and text input by a user?

### ISSUE THREAD

**Issue by leijue222** [linjieli222/VQA_ReGAT#38]
Following the steps in the README, I successfully ran `eval.py`, but it only can give me an eval score. 
So, How can I  **test** your pertained **models** with **image and text input by a user**?

**Comment by linjieli222** [comment]
Thanks for your interests in our project.

Our code does not support testing with raw images, as the feature extraction is done offline. You can try modify the code to add the object detector to have an end-to-end model.

**Comment by leijue222** [comment]
Thanks!
