### ISSUE TITLE
There may be a better memory allocation scheme when loading datasets

### ISSUE THREAD

**Issue by PandaPYH** [linjieli222/VQA_ReGAT#5]
I found this code in dataset.py.

`with h5py.File(h5_path, 'r') as hf:`

      self.features = np.array(hf.get('image_features'))

      self.normalized_bb = np.array(hf.get('spatial_features'))

That will cause huge memory usage. I think you can use some like `feat_dset=hf['image_features'];feat_dset[index]` in \_\_getitem\_\_.

**Comment by linjieli222** [comment]
Thank you for your suggestion.  I have never encountered memory issue during training, but indeed loading them upon initialization of dataset would be occupying some memory.

**Comment by haoopan** [comment]
> I found this code in dataset.py.
> 
> `with h5py.File(h5_path, 'r') as hf:`
> 
> ```
>   self.features = np.array(hf.get('image_features'))
> 
>   self.normalized_bb = np.array(hf.get('spatial_features'))
> ```
> 
> That will cause huge memory usage. I think you can use some like `feat_dset=hf['image_features'];feat_dset[index]` in __getitem__.

Hello,I also meet the problem of MemoryError.Can you share the details about your change? Thanks!

**Comment by ark1234** [comment]
> > I found this code in dataset.py.
> > `with h5py.File(h5_path, 'r') as hf:`
> > ```
> >   self.features = np.array(hf.get('image_features'))
> > 
> >   self.normalized_bb = np.array(hf.get('spatial_features'))
> > ```
> > 
> > 
> > That will cause huge memory usage. I think you can use some like `feat_dset=hf['image_features'];feat_dset[index]` in **getitem**.
> 
> Hello,I also meet the problem of MemoryError.Can you share the details about your change? Thanks!

The code itself is fine, you need more than 73.67GB RAM to run it.

**Comment by BAZINGAC** [comment]
> I found this code in dataset.py.
> with h5py.File(h5_path, 'r') as hf:
>   self.features = np.array(hf.get('image_features'))
> 
>   self.normalized_bb = np.array(hf.get('spatial_features'))
> 
> That will cause huge memory usage. I think you can use some like feat_dset=hf['image_features'];feat_dset[index] in getitem.
> 
> Hello,I also meet the problem of MemoryError.Can you share the details about your change? Thanks!

Hello，I also meet the problem.Have you solved your problem now?
