### ISSUE TITLE
What are the specific categories in your semantic relationship classification?

### ISSUE THREAD

**Issue by ZiheZhou** [linjieli222/VQA_ReGAT#6]
What are the specific categories in your semantic relationship classification?

**Comment by linjieli222** [comment]
Sorry for the late reply. 
Here are the 15 relationships used in my semantic relationship classifier:
no_relation, wearing, sitting on, standing on, riding, eating, hanging from, carrying, attached to, walking on, playing, covering, lying on, watching, looking at
