### ISSUE TITLE
Can you provide a Google Drive link for dataset?

### ISSUE THREAD

**Issue by JackHenry1992** [linjieli222/VQA_ReGAT#7]
Thank you for sharing your perfect job.
Can you provide a Google Drive link for the datasets? It is too slow to download these datasets.

**Comment by tuyunbin** [comment]
Did you download these datasets? I am in China and cannot download these files by using provided .sh file. @JackHenry1992

**Comment by nikhilbchilwant** [comment]
The download speed is very low. Did you find any remedy for this?
