### ISSUE TITLE
Code to build the spatial adjacency matrix 

### ISSUE THREAD

**Issue by yashkant** [linjieli222/VQA_ReGAT#9]
Hi, 

Thanks for sharing the code. Could you also share the code for building the adjacency matrix of spatial relations from bounding boxes?

Thanks.

**Comment by linjieli222** [comment]
Thank you for your interests in this project. You can call this function to build spatial graph: https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/position_emb.py#L41

**Comment by yashkant** [comment]
Thanks for the instant reply @linjieli222, could you help me with these follow-up questions:

1. What is the `spatial` argument which is used below? Also, is bbox[0] the image bounding-box?
https://github.com/linjieli222/VQA_ReGAT/blob/9f6fe5bcda169c268eb1c92ef00df9f61d540081/model/position_emb.py#L57

2. Are the `bbox` coordinates normalized or are they absolute values?

**Comment by linjieli222** [comment]
Sorry about the confusion.
1. spatial here is just normalized bb. It is only used to get image_h and image_w. If you happen to have image_h and image_w in hand, no need to generate normalized bb
2. bbox  is not normalized, just pass it as it is from detection model.
